/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1a1b22",
        "primary-fixed-dim": "#c6c6c7",
        "surface-dim": "#131315",
        "surface-tint": "#c6c6c7",
        "surface-container-low": "#1b1b1d",
        "on-tertiary": "#2f3038",
        "surface-variant": "#353437",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "inverse-primary": "#5d5e60",
        "on-tertiary-fixed-variant": "#46464e",
        "on-primary": "#2f3132",
        "secondary-fixed-dim": "#c6c6cf",
        "primary-container": "#e2e2e3",
        "surface-bright": "#39393b",
        "on-primary-fixed": "#1a1c1d",
        "primary": "#ffffff",
        "secondary-container": "#45464e",
        "outline": "#8e9193",
        "secondary-fixed": "#e2e1eb",
        "on-secondary-container": "#b4b4bd",
        "surface-container": "#201f21",
        "on-primary-fixed-variant": "#454748",
        "on-tertiary-container": "#63646c",
        "outline-variant": "#444749",
        "tertiary-fixed": "#e3e1ec",
        "background": "#131315",
        "surface": "#131315",
        "on-secondary-fixed-variant": "#45464e",
        "tertiary": "#ffffff",
        "inverse-on-surface": "#303032",
        "primary-fixed": "#e2e2e3",
        "error-container": "#93000a",
        "tertiary-container": "#e3e1ec",
        "on-surface": "#e5e1e4",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "inverse-surface": "#e5e1e4",
        "on-secondary-fixed": "#1a1b22",
        "on-surface-variant": "#c4c7c9",
        "on-background": "#e5e1e4",
        "on-secondary": "#2f3037",
        "surface-container-lowest": "#0e0e10",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c6c5cf",
        "on-primary-container": "#636466",
        "secondary": "#c6c6cf",
        // Backward-compat aliases
        lacquer: "#131315",
        substrate: "#1b1b1d",
        paper: "#e5e1e4",
        kraft: "#8e9193",
        scribe: "#353437",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-3xl": "4rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem",
        "player-height": "5.5rem",
        "space-lg": "1.5rem",
        "space-base": "1rem",
        "gutter-queue": "20rem",
        "space-sm": "0.5rem",
        "gutter-sidebar": "16rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
      },
      fontFamily: {
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Inter'", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "mono-numbers": ["'Inter'", "monospace"],
        "display-hero-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "mono-numbers": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-hero-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
